name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  macos:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --sanitize=thread
    - name: Generate documentation
      uses: sukhrobkhakimov/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        args: "--module SQLite --theme fullwidth --root-url https://tuproq.dev/sqlite --source-host github --source-host-url https://github.com/tuproq/sqlite"
